### ISSUE TITLE
Not able to fill details in login page in mobile view. 

### ISSUE THREAD

**Issue by ritik-vashist** [Tejas1510/Athavani#290]
When we open the website in mobile view we are not able to enter details for login because of the banner of joining with us through social media. 
I thinks its a major issue in it.

**Comment by ritik-vashist** [comment]
I would like to work on this issue. 
@Tejas1510  ma'am, 
Could you please assign this task to me? 

Another thing is there are two possible solution for it. 
-that pages is to be hidden in mobile view 
-second possibility is to have a close button in that banner to close that. 

If you assign this task to me ma'am. 
Then I request you to suggest me which option has to be chosen.

**Comment by Tejas1510** [comment]
@ritik-vashist, I am Tejas Tapas so a Male so please don't call me mama 😅

@AmeyaJain-25 take a look into this and assign accordingly to @ritik-vashist

**Comment by ritik-vashist** [comment]
Sorry @Tejas1510 sir.

**Comment by AmeyaJain-25** [comment]
@ritik-vashist 
Go ahead.

Actually it's not a modal or popup which can be closed.
It's the footer and if you login, you can see it on profile and home page too.
What you can do is bring the footer at bottom ( Now it's using position absolute ). Then it will be fine. Because footer is must.
Also after bringing it to bottom, do check this footer in all the pages ( Home, Profile, Signin, Signup, etc )
