### ISSUE TITLE
Improve the layout of Main Page

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Athavani#3]
Modify the MainPage Layout by making the UI better

**Comment by kanishkaa24** [comment]
Hey!
I would love to work on this issue.

**Comment by Tejas1510** [comment]
Go ahead @kanishkaa24

**Comment by Sakshi-25** [comment]
Some improvements that I suggest:

- The more button ( 3 dots) isn't doing anything, Can I add some features to it like:
	- *Explore* : Show other details about the cards, like pictures etc
	- *Expand* : Make the card dimensions bigger and show more info
- Associate a Date with every card to so that we can sort that accordingly. 
- Applying a filter options in the search bar - sort by date, admins, mame, place etc.

Kindly assign these improvements to me @Tejas1510

**Comment by Tejas1510** [comment]
The 3 dots are for Updation purpose so if a user wants to update some info 
But I really like your Idea of Filtering based on various Parameter
You can go ahead on that @Sakshi-25

**Comment by Sakshi-25** [comment]
Kindly assign so that I can make a PR😅

**Comment by Tejas1510** [comment]
@Sakshi-25 you have been Assigned Go Ahead

**Comment by kanishkaa24** [comment]
https://github.com/kanishkaa24/Athavani/blob/master/Memories%20are%20forever.png
This is the link to the image.

**Comment by kanishkaa24** [comment]
What is the required contribution in this issue ?

**Comment by Tejas1510** [comment]
@Sakshi-25 how is your work going with respect to sorting and filtering of card

**Comment by kanishkaa24** [comment]
Is there any contribution required on this issue? @Tejas1510
